#
# @Author: zm
# @Date: 2019-10-13 21:45:10
# @LastEditTime: 2019-10-13 21:46:06
# @Description: file content
# 

name: Net
algorithm:  ugcn_s4nb #arfnet #ugcn_s4nba0
nEpochs: 2000
gpu_mode: True
save_best: True
gpus: [0]
threads: 16  #num_works
log_dir: /home/zm/newpan/log/


seed: 123
checkpoint: /home/zm/newpan/checkpoint
data_dir_train: /home/zm/yaogan/WV2_data/train128
data_dir_eval: /home/zm/yaogan/WV2_data/test128
source_ms: ms
source_pan: pan

pretrain:
  pretrained: False
  pre_sr: GPPNN3_4_1647496009/best_900.pth
  pre_folder: /home/zm/newpan/checkpoint/

test:  #用于指标测试的代码
  algorithm: ugcn_s4nb #arfnet
  type: test #[test, eval]
  data_dir: /home/zm/yaogan/WV2_data/test128
  source_ms: ms
  source_pan: pan
  model: ugcn_s4nb_4_1655633331/best.pth #pannetnipsi_4_1653126019/latest.pth #arfnet_4_1652535888/best.pth  # no softmax latest  best
  # model: GPPNN3_4_1647436525/latest.pth   #softmax
  save_dir: /home/zm/newpan/result/net_WV2

data:
  upsacle:  4
  batch_size: 4 #4
  patch_size: 32
  data_augmentation: False                                                                                                                                                                                               
  n_colors: 4
  rgb_range: 255
  normalize : False
  
schedule:
  lr: 1e-2
  decay1: 1600
  decay2: 1900
  decay3: 2400
  gamma: 0.5
  optimizer: SGD #[ADAM, SGD, RMSprop]
  momentum: 0.9 #SGD momentum
  beta1: 0.9 #ADAM beta
  beta2: 0.999 #ADAM beta
  epsilon: 1e-8 #ADAM epsilon
  alpha: 0.9 #RMSprop alpha
  weight_dency: 0
  gclip: 0.4  #0.4  0.04  -1
  loss: MSE #[MSE, L1]
  use_YCbCr: False

